@host=http://localhost:5197

GET {{host}}/dinners
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwMDAwMDAwMC0wMDAwLTAwMDAtMDAwMC0wMDAwMDAwMDAwMDAiLCJnaXZlbl9uYW1lIjoiVG9tYWFzeiIsImZhbWlseV9uYW1lIjoiTWllc3prb3dpY3oiLCJqdGkiOiJlMzg4NjA5Mi0wZDJjLTQwODYtYmM4NC1hZWVlMzc0ZTkyNjMiLCJleHAiOjE3NDMzMjc5NDgsImlzcyI6IlRvbW1pZURpbm5lciIsImF1ZCI6IlRvbW1pZURpbm5lciJ9.44gc6s74IIOzc1KNrsl5sRt4Fd97pB_JpbhWqPbBDTM
